### ISSUE TITLE
Line numbers when there is a repetition in data in json is not correct

### ISSUE THREAD

**Issue by suneel-lean** [pb33f/wiretap#110]
| Line Number | JSON Path                                                                                        | Issue Description                           |
|-------------|--------------------------------------------------------------------------------------------------|---------------------------------------------|
| 150         | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/BookingDateTime/format                  | '2024-01-15T18:45:14' is not valid 'date-time' |
| 155         | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/ValueDateTime/format                    | '2024-01-15T18:45:14' is not valid 'date-time' |
| 49          | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/TransactionDateTime/format              | '2024-01-15T18:45:14' is not valid 'date-time' |
| 72          | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/TransactionType/enum                   | value must be one of "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx" |
| 49          | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/TransactionDateTime/format              | '2024-01-11T15:39:37' is not valid 'date-time' |
| 72          | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/TransactionType/enum                   | value must be one of "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx", "xxxxxxxx" |
| 155         | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/ValueDateTime/format                    | '2024-01-11T15:39:37' is not valid 'date-time' |
| 150         | /xxxx/xxxx/xxxxx/xxxxxx/items/properties/BookingDateTime/format                  | '2024-01-11T15:39:37' is not valid 'date-time' |

## Issue description
The issue is the line numbers getting printed are incorrect in wiretap UI if the data schema repeats internally representing multiple data set for example transactions

If possible require a immediate fix on the same. Thanks in advance!!

**Comment by daveshanley** [comment]
I really can't help without a sample specification and knowledge of what you're doing. 

Also, this is a free and open source product, donated out of my own free time. Please do not expect `an immediate fix`. It's unlikely to get you very far.

**Comment by suneel-lean** [comment]
Let me work on the sample specification and get back on the same

**Comment by daveshanley** [comment]
I will re-open this once you have a reproducible spec / workflow. I can't help otherwise as the mechanisms that handle line numbers are in a different library of mine.
