### ISSUE TITLE
Wiretap fails to retain the requests which are still loading

### ISSUE THREAD

**Issue by suneel-lean** [pb33f/wiretap#111]
## Issue description
Whenever a synchronous api is being executed the wiretap displays the api in executing status with a loader status, but in between if the user refreshes the wiretap UI, the api request which is being executed vanishes from the UI.  Could not post a screenshot of the same as the details are confidential in the UI

**Comment by daveshanley** [comment]
I cannot help you without a reproducible spec and workflow. Sorry! Wiretap is used in many different ways and I don't know how you're using it or what you're trying to do.

**Comment by suneel-lean** [comment]
I will prepare a sample spec for the same and get back here

**Comment by daveshanley** [comment]
I have tried to re-create this, but I can't. Please come back with workflow I can use to re-create this issue.
