### ISSUE TITLE
Always getting "[Unable to parse JSON body]"

### ISSUE THREAD

**Issue by nichwall** [pb33f/wiretap#119]
I have not been able to get the JSON body to be parsed at all using wiretap (version `0.1.11` at the time of writing, but has been an issue since `0.1.1`).

![image](https://github.com/pb33f/wiretap/assets/5686638/7fd732e5-b330-4634-a589-7b32b88be977)

After some investigation, I think it is due to `jsonBody` instead of `parsedBody` always being used in the case statement (except for a Multipart body).

https://github.com/pb33f/wiretap/blob/3483053ab7ee420cc2cc531ca4c9c818f891b942/ui/src/components/transaction/request-body.ts#L57-L70

**Comment by daveshanley** [comment]
You're right, this was messed up and has been fixed in `v0.1.12`

**Comment by nichwall** [comment]
Confirmed working in `v0.1.12`
