### ISSUE TITLE
start at startup (regression since 1.13)

### ISSUE THREAD

**Issue by LasneF** [pb33f/wiretap#129]
leveraging the command line 

  run `npm fund` for details
wiretap -s .\component-descriptor.yml -u https://myhome.com/mocks/v1/api -p 4010

wiretap version: 0.1.17 | compiled: Wed, 26 Jun 2024 13:46:44 UTC
Designed and built by Princess Beef Heavy Industries: https://pb33f.io/wiretap

 INFO  No wiretap configuration located. Using defaults
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xc3c3dd]

goroutine 1 [running]:
github.com/pb33f/wiretap/cmd.init.func1(0x1e450a0, {0xe9c73c?, 0x4?, 0xe9c5d4?})
        /home/runner/work/wiretap/wiretap/cmd/root_command.go:349 +0x163d
github.com/spf13/cobra.(*Command).execute(0x1e450a0, {0xc0000ca010, 0x6, 0x7})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0x1e450a0)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/pb33f/wiretap/cmd.Execute({0x16a9600?, 0x19?}, {0x16b4900?, 0xeb0042?}, {0xc0001f3d40?, 0x1d81378?}, {0xc00008c000?})
        /home/runner/work/wiretap/wiretap/cmd/root_command.go:683 +0x78b
main.main()
        /home/runner/work/wiretap/wiretap/wiretap.go:35 +0x15f
        
        

Notice that same commandline was working leveraging 1.13 

it s on windows , adding --debug does not help

**Comment by LasneF** [comment]
digging a little bit the 1.17 is broken, the 1.16 as well , the issue does not appears in the 1.15

**Comment by daveshanley** [comment]
Fixed in `v0.1.8`
