### ISSUE TITLE
Fail response when request and/or response don't pass validation

### ISSUE THREAD

**Issue by timur-sokolov** [pb33f/wiretap#38]
Add a new configuration-driven possibility to fail proxied request-response when the request and/or response don't pass OpenAPI validation. 
For example, add a boolean configuration parameter that will trigger to return an unsuccessful status code from wiretap when a request and/or response don't pass OpenAPI validation. Maybe, the second configuration parameter with error status code.
Goal - use wiretap in the pipeline with any API mock and get an error when mocked request and/or response don't pass OpenAPI validation

**Comment by daveshanley** [comment]
Try `v0.0.33`. 

Use the new `-e` flag to turn on 'hard-validation' mode, which will return a default of `400` as a status code on API requests that fail validation and `502` on failed responses. 

These codes can be overridden using `q` to set the error code for failed requests and `y` to set the error code for failed responses.

The configuration values can be set in the config file.

```
hardValidation: true
hardValidationCode: 422
hardValidationReturnCode: 500
```

**Comment by daveshanley** [comment]
Actually try `v0.0.34` there is a UI bug in 0.0.33
