### ISSUE TITLE
Bug : Glitch on % display on error level

### ISSUE THREAD

**Issue by LasneF** [pb33f/wiretap#46]
in some circunstances the computation of the compliance rate kind of over flow 

![image](https://github.com/pb33f/wiretap/assets/12461661/4f90562b-0100-4786-b504-1e63791c2742)

check the image , 
compliance should be rounded to unit , like here 84% would be enough

**Comment by daveshanley** [comment]
I had to edit this exact bug out of the walkthrough video :D
