### ISSUE TITLE
Feature Request : Simple path URL  / Base Path rewrite 

### ISSUE THREAD

**Issue by LasneF** [pb33f/wiretap#50]
Given an API specification that defines /ranch 

given an backend running on mymachine with a basepath , so responding on

http://mymachine/aBasePath/ThatcanbeseveralsSegments/ranch

it would be nice that 
given the wiretab command line : 
wiretap -s .\mySpec.yml -u http://mymachine/aBasePath/ThatcanbeseveralsSegments/

that it runs auto magically , ie that when a call is comming on http://wiretapProxy/ranch it goes directed to http://mymachine/aBasePath/ThatcanbeseveralsSegments/ranch without doing more settings

**Comment by daveshanley** [comment]
This should be possible technically already in the existing code, I think I have forgotten to wire something up here. Will investigate.

**Comment by LasneF** [comment]
after few missconfiguration from my side, i got it ...  a bit working , but
this is still raising an issue 

"
The POST request contains a path of 'aBasePath/ThatcanbeseveralsSegments/ranch' however that path, or the POST method for that path does not exist in the specification

How to fix this violation:
Check the path is correct, and check that the correct HTTP method has been used (e.g. GET, POST, PUT, DELETE)
" 

looks still something wrong 
what would be nice is

if spec define /ranch , 
if backend handle it in /basepath/ranch 
i should be able to do from client something like /basepath/ranch  so that it act as a transparent proxy (no custom setting on client if with or without proxy just host)

**Comment by LasneF** [comment]
checked with spectral 🥺 here i succeed to make it works , so yes would be good to have such 

here is another same kind of use case  / failure a bit easier i guess to set

even if traces says 
 INFO  API Gateway is now proxying all traffic to 'http://127.0.0.1:8181/mocks/v1/api/'
 
 i do a call on http://host/ranch ... it is proxy to http://127.0.0.1/ranch  :( (ie no path added ) 
 
so there is something to do with support of 
1. host/abasePath / WhatIsInSpec  going to  targethost/abasePath/WhatisinSpec 
2. host/WhatisSpec going to targethost/abasePath/WhatisinSpec   
using -u option 
use case 2 beeing more usefull, use case 1 beeing nice to have

**Comment by LasneF** [comment]
after several round of config make my case running so my fault
