### ISSUE TITLE
AllowFileLookup config doesn't exist

### ISSUE THREAD

**Issue by AlexBroadbent** [pb33f/wiretap#52]
My OpenAPI 3.1 spec uses references within other files, but the configuration in the error response doesn't seem to work.

<img width="976" alt="Screenshot 2023-10-08 at 22 53 09" src="https://github.com/pb33f/wiretap/assets/3311606/6de51c02-cfc0-488d-8949-2258e6a169a4">

**Comment by daveshanley** [comment]
Hi, 

This is the same issue as: https://github.com/pb33f/openapi-changes/issues/65

The capability is there, it just has not been wired up yet, this configuration is actually something handled much lower in the stack via [libopenapi](/pb33f/libopenapi).

It just needs to be correctly wired up and allow base paths and URLs for exploded references.

**Comment by daveshanley** [comment]
No longer required in `v0.0.40`

Refs are auto resolved remotely or from the current working directory. If the refs are in a different working dir, then the new `--base` flag can be used to set the working base path.
