### ISSUE TITLE
Add support for HAR files

### ISSUE THREAD

**Issue by daveshanley** [pb33f/wiretap#55]
Allow wiretap to import HAR files and show the replay in the monitor UI, complete with compliance check on OpenAPI spec.  I should be able to run this as a headless command and have the tool spit out a compliance report to stout or a file.

**Comment by mknj** [comment]
https://github.com/Stuk/server-replay + https://github.com/testable/har-replay ?

The word replay suggests that the requests in the har file are really re-executed against the real target. So if you don't want to replay, it is more an 'offline HAR file analysis'

**Comment by daveshanley** [comment]
It's not a replay no, it's an 'offline analysis' or 'review what happened' feature.

**Comment by daveshanley** [comment]
This has been implemented in `v0.1.0` 

https://pb33f.io/wiretap/har-files/
