### ISSUE TITLE
Reset State button should reset numbers

### ISSUE THREAD

**Issue by LasneF** [pb33f/wiretap#56]
As of today the reset state button reset the "call panel" on the left 
but it does not reset the statistics about number of call and success 

it should (my opinion) or have a way to do it via a tick ( not sure as will make ui with plenty of tick in few years )

**Comment by daveshanley** [comment]
With the latest version of wiretap, I cannot re-create this. 

Here is a video that showcases the statistics


https://github.com/pb33f/wiretap/assets/187345/7f9152c3-3d42-415e-911b-cb2b0727a778

**Comment by LasneF** [comment]
@daveshanley  tested and validated you can close this one now
