### ISSUE TITLE
encountered panic after 4 requests are validated in wiretap

### ISSUE THREAD

**Issue by pranayinos** [pb33f/wiretap#69]
The Panic was:

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0xa4db8a]

goroutine 3406 [running]:github.com/pb33f/libopenapi-validator/requests.(requestBodyValidator).ValidateRequestBody(0xc00878e900, 0xc003411700)
    /go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.33/requests/validate_body.go:32 +0x16a
github.com/pb33f/libopenapi-validator.(validator).ValidateHttpRequest.func2(0x0?, 0x0?)
    /go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.33/validator.go:247 +0x30
created by github.com/pb33f/libopenapi-validator.(*validator).ValidateHttpRequest in goroutine 3422
    /go/pkg/mod/github.com/pb33f/libopenapi-validator@v0.0.33/validator.go:267 +0x332`

command used to run wiretap:
`wiretap -u https://my-api-server-url.com/ --ws-host localhost -s smoke.json`

**Comment by daveshanley** [comment]
These issues should have been resolved in the latest version of the validator. Wiretap has been updated, can you try the latest?

**Comment by daveshanley** [comment]
@pranayinos Did it work for you?

**Comment by daveshanley** [comment]
Cannot replicate this issue anymore. Closing.

**Comment by pranayinos** [comment]
Sorry for late reply, I can see this issue is fixed. Thank you!!
