### ISSUE TITLE
Percentage computation

### ISSUE THREAD

**Issue by LasneF** [pb33f/wiretap#74]
![image](https://github.com/pb33f/wiretap/assets/12461661/09d51a59-07da-41d8-81ea-204e9cc5011d)

given the fact that for a given request there is validation of the inbound + validation of the outbound i cannot get how we get to 75%

could be 0 % compliance , if we consider the round trip , could be 50 % if we consider that it is 2 check one succeed , and one fail but not 75% 

notice that if i repeat it keeps it to 75%

**Comment by daveshanley** [comment]
Yeah, this logic is totally messed up. I've been meaning to fix it. Thank you for bumping it up my queue.

**Comment by daveshanley** [comment]
This has been fixed in `v0.1.0`
