### ISSUE TITLE
Path with Fragment is not handled as expected

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/wiretap#78]
Consider this example spec:

```yaml
openapi: 3.1.0
info:
  title: Test
  version: 0.1.0
security:
  - apiKeyAuth: []
paths:
  /auth#basicAuth:
    post:
      operationId: basicAuth
      security:
        - basicAuth: []
      servers:
        - url: http://localhost:35456
      requestBody:
        content:
          application/json:
            schemas:
              type: object
        required: true
      responses:
        "200":
          description: OK
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic

```

wiretap will return the below error when sending a request to `/auth`

```json
{"type":"https://pb33f.io/wiretap/error","title":"unable to serve mocked response","status":404,"detail":"Error: POST Path '/auth' not found, Reason: The POST request contains a path of '/auth' however that path, or the POST method for that path does not exist in the specification"}
```

Using a fragment in the OpenAPI spec is a pretty common way of reusing a path multiple times ie `/auth#instance1` and `/auth#instance2` so for the same path & method combination a different schema can be provided instead of needing to use `oneOf` for example on the request/response bodies.

**Comment by daveshanley** [comment]
Nice gap. Never thought about fragments in paths.

**Comment by daveshanley** [comment]
Supported in `v0.1.1`

**Comment by daveshanley** [comment]
Supported is a strong term, after deeper investigation as a part of #96, it seems fragments cannot be supported as delimiters.

**Comment by TristanSpeakEasy** [comment]
As mentioned in this comment it could be technically possible to handle ie treat it as deserializing a oneOf of the two request bodies as an example https://github.com/pb33f/wiretap/issues/88#issuecomment-2092441446

**Comment by daveshanley** [comment]
I would be willing to make the fragment work as a delimiter, if it wasn't just a browser concept (I never really gave it much thought to be honest). However because it is just a browser concept and isn't actually part of HTTP or even OpenAPI in any meaningful way, I think I am going to keep this as a wontfix for now, 

Happy to accept a contribution however.
