### ISSUE TITLE
Mock response didn't return the expected example data

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/wiretap#84]
This may be a bad assumption on my part but I would expect (or want) the responses returned by wiretap in mock mode to use the provided examples if in the spec and only provide truly mocked responses (ie generating responses based on the schema) if there were no provided examples.

If this isn't the intended behavior or my assumption was wrong would be good if it could be configured to react this way?

**Comment by TristanSpeakEasy** [comment]
So this is likely to be a feature request I imagine.

It would be great to have a feature flag that determines whether fully mocked or partially mocked data is returned.

So in fully mocked mode it returns random generated data and in partial mode it returns any examples defined in the openapi documentation, just filling in the missing examples with generated data.

Another configuration might also be to determine how the defined examples are returned, do you round robin return the examples if there are multiple of them provided, or deterministically return only the first examples in the list (with an exception for arrays etc)

**Comment by daveshanley** [comment]
This is actually a bug, it should always flow from object examples, to schema examples and then to inline example values within schemas and then generated values.

**Comment by daveshanley** [comment]
This should be resolved in `v0.1.1`

The default behavior is: 

Look for `Examples` first, pick the first named example it finds (if using labels) or the first item in the index (if using an index). This choice can be overridden by using the `Preferred` header, using the label name, or the index value.

If there are no `Examples` then the `Example` value is used.

If there is no `Example` value, then the mock engine attempts to generate a value.
