### ISSUE TITLE
Install not working using a Windows environment 

### ISSUE THREAD

**Issue by LasneF** [pb33f/wiretap#86]
PS D:\tmp\developer-portal> npm i -g @pb33f/openapi-changes
npm ERR! code 1
npm ERR! path C:\Users\XXX\AppData\Roaming\npm\node_modules\@pb33f\openapi-changes
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node ./npm-install/postinstall.js
npm ERR! fetching from URL https://github.com/pb33f/openapi-changes/releases/download/v0.0.53/openapi-changes_0.0.53_windows_x86_64.zip
npm ERR! Error: ENOENT: no such file or directory, chmod './bin/openapi-changes'
npm ERR!     at Module.chmodSync (node:fs:1916:3)
npm ERR!     at install (file:///C:/Users/XXX/AppData/Roaming/npm/node_modules/@pb33f/openapi-changes/npm-install/postinstall.js:54:14)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
npm ERR!   errno: -4058,
npm ERR!   syscall: 'chmod',
npm ERR!   code: 'ENOENT',
npm ERR!   path: './bin/openapi-changes'
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXX\AppData\Local\npm-cache\_logs\2024-01-25T11_16_47_112Z-debug-0.log

**Comment by daveshanley** [comment]
strange, will investigate

**Comment by LasneF** [comment]
sorry wrong repo :(
