### ISSUE TITLE
wiretap fails to authenticate a operation that uses the same route but unique via a fragment

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/wiretap#88]
This is related to this new change I believe: https://github.com/pb33f/wiretap/issues/78

For this spec:

```yaml
openapi: 3.1.0
info:
  title: Test
  version: 0.1.0
security:
  - apiKeyAuth: []
  - apiKeyAuthNew: []
  - oauth2: []
  - {}
paths:
  /auth#basicAuth:
    post:
      operationId: basicAuthNew
      security:
        - basicAuth: []
      servers:
        - url: http://localhost:35456
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/authServiceRequestBody"
        required: true
      responses:
        "200":
          description: OK
        "401":
          description: Unsuccessful authentication.
  /auth#apiKeyAuthGlobal:
    post:
      operationId: apiKeyAuthGlobalNew
      servers:
        - url: http://localhost:35456
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/authServiceRequestBody"
        required: true
      responses:
        "200":
          description: OK
        "401":
          description: Unsuccessful authentication.
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
      x-speakeasy-example: YOUR_USERNAME;YOUR_PASSWORD
    apiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: Authenticate using an API Key generated via our platform.
      x-speakeasy-example: Token YOUR_API_KEY
    bearerAuth:
      type: http
      scheme: bearer
      x-speakeasy-example: YOUR_JWT
    apiKeyAuthNew:
      type: apiKey
      in: header
      name: x-api-key
      x-speakeasy-example: Token <YOUR_API_KEY>
    oauth2:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:35123/oauth2/authorize
          scopes: {}
      x-speakeasy-example: Bearer YOUR_OAUTH2_TOKEN
    openIdConnect:
      type: openIdConnect
      openIdConnectUrl: http://localhost:35123/.well-known/openid-configuration
      x-speakeasy-example: Bearer YOUR_OPENID_TOKEN
  schemas:
    authServiceRequestBody:
      type: object
      properties:
        headerAuth:
          type: array
          items:
            type: object
            properties:
              headerName:
                type: string
              expectedValue:
                type: string
            required:
              - headerName
              - expectedValue
        basicAuth:
          type: object
          properties:
            username:
              type: string
            password:
              type: string
          required:
            - username
            - password
```

Trying to do a request against the operation `apiKeyAuthGlobalNew` fails with the below error:

```json
{"type":"https://pb33f.io/wiretap/error","title":"unable to serve mocked response","status":401,"detail":"basic authentication failed: bearer token not found, no `Authorization` header found in request"}
```

It looks to not be matching the right route and expecting the basic auth of the `basicAuthNew` operation

**Comment by daveshanley** [comment]
As mentioned in #96 

After attempting to solve this, I was confused as to why the correct path could not be found. 

The `http.Request.URL.Fragment` was always missing when making a curl request or via postman etc. I was unable to perform any kind of lookup when a fragment was used, because any request made to wiretap using a fragment was just missing the fragment each time. 

So then I looked a little deeper. I found this: 

https://github.com/golang/go/issues/3805

```
Fragments are never sent in HTTP.  They're purely a local browser concept.
```

There is no way for me determine which path is being requested when the OpenAPI specification uses a fragment as a delimiter. The fragment is never picked up by the standard library. 

Which pulls into question the legitimacy of using fragments at all in OpenAPI specs. They are quite useless it seems and should not be used as delimiters for paths.

Marking this as a wontfix, because there is nothing I can do to make it work.

**Comment by TristanSpeakEasy** [comment]
@daveshanley a strategy we are seeing people using to deal with this is it effectively becomes a join of the two operations, on their servers the two routes or directed to the same handler but they are determining the operation based on the inputs, so it is effectively a `oneOf` between the request bodies/response bodies etc.

Totally understand if you want to keep this as wontfix, we can find some other way to deal with this but it is theoretically possible

**Comment by daveshanley** [comment]
I think this strategy is a little bit odd to be honest, it means parsing the body to determine the schema, in order to figure out which fragment to use - which to me feels like a considerable hack. It feels like it's going against the spirit of the standard, in order to make it work.

**Comment by TristanSpeakEasy** [comment]
So technically yes it does look like the OpenAPI initiative has decided to not make this official https://github.com/OAI/OpenAPI-Specification/issues/1635 but in the wild it is getting used to differentiate APIs that share a path but can accept different request bodies, we have come across a few cases of this and various tooling does seem to support it (including ours)
